version: '3.3'

services:
  db:
    build: ./db
    container_name: postgres
    ports:
      - "5431:6666"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inspections_db
    volumes:
      - ./data:/data
  app:
    build: ../inspection-app/
    container_name: app
    depends_on:
      - db